language: python
python: 3.7

dist: xenial

services:
  - docker

before_install:
  - make mysql-container
  - make postgres-container

install:
  - pip install tox

matrix:
  include:
    - python: 3.7
      env: TOX_ENV="py37-sqlalchemy1.4"

    - python: 3.8
      env: TOX_ENV="py38-sqlalchemy1.4"
    
    - python: 3.9
      env: TOX_ENV="py39-sqlalchemy1.4"
    
    - python: 3.10
      env: TOX_ENV="py310-sqlalchemy1.4"

script:
  - tox -e $TOX_ENV
